// Generated by `python -m hpc_assistant_backend sync-opencode-tools`.
// Edit the Python registry in `backend/src/hpc_assistant_backend/opencode_tools.py`.

import { tool } from "@opencode-ai/plugin"
import { runPythonTool } from "./_python"

export const list = tool({
  description: "List directory contents inside approved filesystem roots.",
  args: {
    path: tool.schema.string().describe("Directory to inspect.").optional(),
    long: tool.schema.boolean().describe("Use the long ls view.").optional(),
    all_entries: tool.schema.boolean().describe("Include dotfiles.").optional(),
  },
  async execute(args, context) {
    return await runPythonTool("filesystem_list", args, context)
  },
})

export const head = tool({
  description: "Read the first lines of a file inside approved filesystem roots.",
  args: {
    path: tool.schema.string().describe("File path."),
    lines: tool.schema.number().int().describe("Number of lines to read.").optional(),
  },
  async execute(args, context) {
    return await runPythonTool("filesystem_head", args, context)
  },
})

export const remove = tool({
  description: "Remove a file or directory inside approved filesystem roots.",
  args: {
    path: tool.schema.string().describe("Path to remove."),
    recursive: tool.schema.boolean().describe("Use recursive removal.").optional(),
    force: tool.schema.boolean().describe("Ignore missing targets.").optional(),
  },
  async execute(args, context) {
    return await runPythonTool("filesystem_remove", args, context)
  },
})

