// Generated by `python -m hpc_assistant_backend sync-opencode-tools`.
// Edit the Python registry in `backend/src/hpc_assistant_backend/opencode_tools.py`.

import { tool } from "@opencode-ai/plugin"
import { runPythonTool } from "./_python"

export const avail = tool({
  description: "Inspect available Lmod or Environment Modules entries.",
  args: {
    query: tool.schema.string().describe("Optional module query.").optional(),
  },
  async execute(args, context) {
    return await runPythonTool("module_avail", args, context)
  },
})

export const spider = tool({
  description: "Inspect all possible modules, or details for a specific module.",
  args: {
    query: tool.schema.string().describe("Optional module query.").optional(),
  },
  async execute(args, context) {
    return await runPythonTool("module_spider", args, context)
  },
})

export const list = tool({
  description: "Inspect the currently visible module state.",
  args: {

  },
  async execute(args, context) {
    return await runPythonTool("module_list", args, context)
  },
})

export const load = tool({
  description: "Load a module into the session environment.",
  args: {
    module_name: tool.schema.string().describe("Module name."),
  },
  async execute(args, context) {
    return await runPythonTool("module_load", args, context)
  },
})

export const unload = tool({
  description: "Unload a module from the session environment.",
  args: {
    module_name: tool.schema.string().describe("Module name."),
  },
  async execute(args, context) {
    return await runPythonTool("module_unload", args, context)
  },
})

export const swap = tool({
  description: "Swap one module for another.",
  args: {
    old_module_name: tool.schema.string().describe("Currently loaded module."),
    new_module_name: tool.schema.string().describe("Replacement module."),
  },
  async execute(args, context) {
    return await runPythonTool("module_swap", args, context)
  },
})

export const purge = tool({
  description: "Purge all loaded modules.",
  args: {

  },
  async execute(args, context) {
    return await runPythonTool("module_purge", args, context)
  },
})

export const use = tool({
  description: "Add a module search path.",
  args: {
    module_path: tool.schema.string().describe("Module path."),
  },
  async execute(args, context) {
    return await runPythonTool("module_use", args, context)
  },
})

export const unuse = tool({
  description: "Remove a module search path.",
  args: {
    module_path: tool.schema.string().describe("Module path."),
  },
  async execute(args, context) {
    return await runPythonTool("module_unuse", args, context)
  },
})

