// Generated by `python -m hpc_assistant_backend sync-opencode-tools`.
// Edit the Python registry in `backend/src/hpc_assistant_backend/opencode_tools.py`.

import { tool } from "@opencode-ai/plugin"
import { runPythonTool } from "./_python"

export const queue = tool({
  description: "Inspect the Slurm queue with common squeue filters.",
  args: {
    user: tool.schema.string().describe("Filter by Slurm user.").optional(),
    partition: tool.schema.string().describe("Filter by Slurm partition.").optional(),
    states: tool.schema.string().describe("Comma-separated Slurm states.").optional(),
    jobs: tool.schema.string().describe("Comma-separated job ids or ranges.").optional(),
    nodes: tool.schema.string().describe("Node list filter.").optional(),
    name: tool.schema.string().describe("Job-name filter.").optional(),
  },
  async execute(args, context) {
    return await runPythonTool("slurm_queue", args, context)
  },
})

export const queue_long = tool({
  description: "Inspect the Slurm queue with an extended column view.",
  args: {
    user: tool.schema.string().describe("Filter by Slurm user.").optional(),
    partition: tool.schema.string().describe("Filter by Slurm partition.").optional(),
    states: tool.schema.string().describe("Comma-separated Slurm states.").optional(),
    jobs: tool.schema.string().describe("Comma-separated job ids or ranges.").optional(),
    nodes: tool.schema.string().describe("Node list filter.").optional(),
    name: tool.schema.string().describe("Job-name filter.").optional(),
  },
  async execute(args, context) {
    return await runPythonTool("slurm_queue_long", args, context)
  },
})

export const job_details = tool({
  description: "Inspect a single Slurm job with scontrol.",
  args: {
    job_id: tool.schema.string().describe("Slurm job id."),
  },
  async execute(args, context) {
    return await runPythonTool("slurm_job_details", args, context)
  },
})

export const partition_details = tool({
  description: "Inspect Slurm partition details with scontrol.",
  args: {
    partition: tool.schema.string().describe("Partition name.").optional(),
  },
  async execute(args, context) {
    return await runPythonTool("slurm_partition_details", args, context)
  },
})

export const node_details = tool({
  description: "Inspect Slurm node details with scontrol.",
  args: {
    nodes: tool.schema.string().describe("Node or node set.").optional(),
  },
  async execute(args, context) {
    return await runPythonTool("slurm_node_details", args, context)
  },
})

export const partitions = tool({
  description: "Inspect Slurm partitions and aggregate node availability via sinfo.",
  args: {
    partition: tool.schema.string().describe("Partition name.").optional(),
    states: tool.schema.string().describe("Comma-separated Slurm states.").optional(),
    summarize: tool.schema.boolean().describe("Use sinfo --summarize.").optional(),
    all_partitions: tool.schema.boolean().describe("Include hidden partitions.").optional(),
    exact: tool.schema.boolean().describe("Require exact matching.").optional(),
  },
  async execute(args, context) {
    return await runPythonTool("slurm_partitions", args, context)
  },
})

export const node_status = tool({
  description: "Inspect node-centric Slurm status via sinfo.",
  args: {
    partition: tool.schema.string().describe("Partition name.").optional(),
    nodes: tool.schema.string().describe("Node or node set.").optional(),
    states: tool.schema.string().describe("Comma-separated Slurm states.").optional(),
    exact: tool.schema.boolean().describe("Require exact matching.").optional(),
    responding_only: tool.schema.boolean().describe("Show only responding nodes.").optional(),
    dead_only: tool.schema.boolean().describe("Show only dead nodes.").optional(),
    future: tool.schema.boolean().describe("Include future nodes.").optional(),
  },
  async execute(args, context) {
    return await runPythonTool("slurm_node_status", args, context)
  },
})

export const node_reasons = tool({
  description: "Inspect unavailable-node reason strings via sinfo.",
  args: {
    partition: tool.schema.string().describe("Partition name.").optional(),
    nodes: tool.schema.string().describe("Node or node set.").optional(),
    states: tool.schema.string().describe("Comma-separated Slurm states.").optional(),
  },
  async execute(args, context) {
    return await runPythonTool("slurm_node_reasons", args, context)
  },
})

export const reservations = tool({
  description: "Inspect active Slurm reservations via sinfo.",
  args: {
    partition: tool.schema.string().describe("Partition name.").optional(),
  },
  async execute(args, context) {
    return await runPythonTool("slurm_reservations", args, context)
  },
})

export const sstat = tool({
  description: "Inspect CPU, memory, and I/O stats for a running job step.",
  args: {
    job_id: tool.schema.string().describe("Slurm job id."),
    allsteps: tool.schema.boolean().describe("Include all job steps.").optional(),
    noconvert: tool.schema.boolean().describe("Disable unit conversion.").optional(),
  },
  async execute(args, context) {
    return await runPythonTool("slurm_sstat", args, context)
  },
})

export const cancel_job = tool({
  description: "Cancel a Slurm job.",
  args: {
    job_id: tool.schema.string().describe("Slurm job id."),
    signal: tool.schema.string().describe("Optional scancel signal.").optional(),
  },
  async execute(args, context) {
    return await runPythonTool("slurm_cancel_job", args, context)
  },
})

